const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  getProjectState: () => ipcRenderer.invoke('get-project-state'),
  chooseProjectFolder: () => ipcRenderer.invoke('choose-project-folder'),
  scanProject: () => ipcRenderer.invoke('scan-project'),
  loadProducts: (paths) => ipcRenderer.invoke('load-products', paths),
  readOverlay: () => ipcRenderer.invoke('read-overlay'),
  saveOverlay: (data) => ipcRenderer.invoke('save-overlay', data),
  getProjectTitle: () => ipcRenderer.invoke('get-project-title'),
  exportXLSX: (data) => ipcRenderer.invoke('export-xlsx', data),
  exportPDF: (data) => ipcRenderer.invoke('export-pdf', data),
  getConfig: () => ipcRenderer.invoke('get-config'),
  saveConfig: (config) => ipcRenderer.invoke('save-config', config),
  getCalcWorkbookConfig: () => ipcRenderer.invoke('get-calc-workbook-config'),
  chooseCalcWorkbook: () => ipcRenderer.invoke('choose-calc-workbook'),
  writeCalcWorkbook: (db, roomName) => ipcRenderer.invoke('write-calc-workbook', { db, roomName }),
  getFitRules: () => ipcRenderer.invoke('get-fit-rules'),
  saveFitRules: (rules) => ipcRenderer.invoke('save-fit-rules', rules),
  getFitRulesData: () => ipcRenderer.invoke('get-fit-rules-data'),
  setFitRulesContext: (ctx) => ipcRenderer.invoke('set-fit-rules-context', ctx),
  openFitRulesWindow: () => ipcRenderer.invoke('open-fit-rules-window'),
  onFitRulesUpdated: (cb) => ipcRenderer.on('fit-rules-updated', () => cb()),
  exportSettings: (payload) => ipcRenderer.invoke('export-settings', payload),
  importSettings: () => ipcRenderer.invoke('import-settings'),
  viyarproGetStatus: () => ipcRenderer.invoke('viyarpro-get-status'),
  viyarproSaveCredentials: (payload) => ipcRenderer.invoke('viyarpro-save-credentials', payload),
  viyarproPickAndSend: () => ipcRenderer.invoke('viyarpro-pick-and-send'),
  viyarproMergeMaterial: (payload) => ipcRenderer.invoke('viyarpro-merge-material', payload),
  viyarproGetDebugLog: () => ipcRenderer.invoke('viyarpro-get-debug-log'),
  onViyarProProgress: (cb) => ipcRenderer.on('viyarpro-progress', (e, phase) => cb(phase)),
  getAppInfo: () => ipcRenderer.invoke('get-app-info'),
  checkUpdate: () => ipcRenderer.invoke('check-update'),
  applyUpdate: (info) => ipcRenderer.invoke('apply-update', info),
  onUpdateAvailable: (cb) => ipcRenderer.on('update-available', (e, info) => cb(info)),
  windowMinimize: () => ipcRenderer.invoke('window-minimize'),
  windowMaximize: () => ipcRenderer.invoke('window-maximize'),
  windowClose: () => ipcRenderer.invoke('window-close')
});
