const fs = require('fs');
const path = require('path');

// Merge multiple v27 .project files (one per product, same material) into one.
// Each source file was generated by ExportViyar.js for a single material of a single model,
// so it has exactly one "sheet" material + N "band" materials + details + optional products.
//
// Merge rules:
//  - sheet material is taken from the first file (they must all be the same material).
//  - band materials are unioned across files, keyed by article|name|height|thickness,
//    and get remapped global ids (2, 3, 4...). Inside each detail the edge "param" and
//    corner "edgeMaterial" attributes are remapped to the new ids.
//  - details are collected from all files and renumbered sequentially.
//  - products/furns are collected from all files and renumbered sequentially.
//  - operation ids inside details already restart per detail -> no conflict.

function windows1251Chars() {
  const cp = [
    0x0402,0x0403,0x201A,0x0453,0x201E,0x2026,0x2020,0x2021,
    0x20AC,0x2030,0x0409,0x2039,0x040A,0x040C,0x040B,0x040F,
    0x0452,0x2018,0x2019,0x201C,0x201D,0x2022,0x2013,0x2014,
    0x0000,0x2122,0x0459,0x203A,0x045A,0x045C,0x045B,0x045F,
    0x00A0,0x040E,0x045E,0x0408,0x00A4,0x0490,0x00A6,0x00A7,
    0x0401,0x00A9,0x0404,0x00AB,0x00AC,0x00AD,0x00AE,0x0407,
    0x00B0,0x00B1,0x0406,0x0456,0x0491,0x00B5,0x00B6,0x00B7,
    0x0451,0x2116,0x0454,0x00BB,0x0458,0x0405,0x0455,0x0457,
    0x0410,0x0411,0x0412,0x0413,0x0414,0x0415,0x0416,0x0417,
    0x0418,0x0419,0x041A,0x041B,0x041C,0x041D,0x041E,0x041F,
    0x0420,0x0421,0x0422,0x0423,0x0424,0x0425,0x0426,0x0427,
    0x0428,0x0429,0x042A,0x042B,0x042C,0x042D,0x042E,0x042F,
    0x0430,0x0431,0x0432,0x0433,0x0434,0x0435,0x0436,0x0437,
    0x0438,0x0439,0x043A,0x043B,0x043C,0x043D,0x043E,0x043F,
    0x0440,0x0441,0x0442,0x0443,0x0444,0x0445,0x0446,0x0447,
    0x0448,0x0449,0x044A,0x044B,0x044C,0x044D,0x044E,0x044F
  ];
  const chars = new Array(256);
  for (let i = 0; i < 128; i++) chars[i] = String.fromCharCode(i);
  for (let i = 0; i < 128; i++) chars[i + 128] = String.fromCharCode(cp[i]);
  return chars;
}

const WIN1251 = windows1251Chars();

function decodeCp1251(buf) {
  let text = buf.toString('utf-8');
  if (text.includes('\uFFFD') || /[\u0800-\uFFFF]/.test(text)) {
    text = buf.toString('latin1').replace(/[\u0080-\u00FF]/g, ch => WIN1251[ch.charCodeAt(0)] || ch);
  }
  return text;
}

function encodeWindows1251(text) {
  const reverse = {};
  for (let i = 0x80; i < 256; i++) {
    const u = WIN1251[i];
    if (u && reverse[u] === undefined) reverse[u] = i;
  }
  const out = [];
  for (let i = 0; i < text.length; i++) {
    const code = text.charCodeAt(i);
    if (code < 0x80) out.push(code);
    else if (reverse[text[i]] !== undefined) out.push(reverse[text[i]]);
    else out.push(0x3F); // '?'
  }
  return Buffer.from(out);
}

// Parse attributes of a self-closing tag into a { '-attr': value } hash (like ObjTree).
function parseSelfClosing(tag) {
  const m = tag.match(/^<(\w+)(.*?)\/>$/s);
  if (!m) return null;
  const node = {};
  let rest = m[2];
  const attrRe = /([\w-]+)\s*=\s*"([^"]*)"/g;
  let am;
  while ((am = attrRe.exec(rest)) !== null) {
    node['-' + am[1]] = am[2];
  }
  return node;
}

// Serialize a self-closing tag from a { '-attr': value } hash (+ optional prefix/indent).
function selfClosingTag(name, attrHash) {
  let s = '<' + name;
  Object.keys(attrHash).forEach(k => {
    if (k.charAt(0) === '-') s += ' ' + k.slice(1) + '="' + String(attrHash[k]) + '"';
  });
  s += ' />';
  return s;
}

// Extract all open/close tag siblings between two markers using a level counter.
function extractBlocks(source, tagName, startIdx) {
  const blocks = [];
  const openRe = new RegExp('<' + tagName + '(?=[\\s>])', 'g');
  const closeRe = new RegExp('</' + tagName + '\\s*>', 'g');
  // Find all <tag ...> and </tag> positions after startIdx
  const opens = [];
  let m;
  openRe.lastIndex = startIdx;
  while ((m = openRe.exec(source)) !== null) opens.push(m.index);
  const closes = [];
  closeRe.lastIndex = startIdx;
  while ((m = closeRe.exec(source)) !== null) closes.push(m.index);

  let level = 0;
  let blockStart = -1;
  let pi = 0, pj = 0;
  const all = [];
  while (pi < opens.length || pj < closes.length) {
    const nextOpen = pi < opens.length ? opens[pi] : Infinity;
    const nextClose = pj < closes.length ? closes[pj] : Infinity;
    if (nextOpen < nextClose) {
      if (level === 0) blockStart = nextOpen;
      level++;
      pi++;
    } else if (nextClose < nextOpen) {
      level--;
      pj++;
      if (level === 0 && blockStart !== -1) {
        blocks.push(source.slice(blockStart, nextClose + tagName.length + 2));
        blockStart = -1;
      }
    } else {
      break;
    }
  }
  return blocks;
}

// Merge .project files. Returns object { material, buffer } where buffer is cp1251.
function mergeProjectFiles(filePaths, opts) {
  opts = opts || {};
  const sources = filePaths.map(p => decodeCp1251(fs.readFileSync(p)));

  // --- Parse each source ------------------------------------------------
  const parsed = [];
  const bandMap = new Map(); // key -> id (starts at 2; id 1 is the sheet)
  let nextBandId = 2;

  for (let si = 0; si < sources.length; si++) {
    const src = sources[si];
    const rec = { materials: [], details: [], products: [] };
    parsed.push(rec);

    // materials block: <material .../> self-closing tags
    const matsStart = src.indexOf('<materials>');
    const matsEnd = src.indexOf('</materials>');
    if (matsStart !== -1 && matsEnd !== -1) {
      const body = src.slice(matsStart + 11, matsEnd);
      const tagRe = /<material\s[^>]*\/>/g;
      let m;
      while ((m = tagRe.exec(body)) !== null) {
        const node = parseSelfClosing(m[0]);
        if (node) {
          node._tag = m[0];
          rec.materials.push(node);
        }
      }
    }

    // details block: <detail ...>...</detail> possibly nested (unlikely but handle)
    const detStart = src.indexOf('<details>');
    const detEnd = src.indexOf('</details>');
    if (detStart !== -1 && detEnd !== -1) {
      const blocks = extractBlocks(src, 'detail', detStart + 9);
      rec.details = blocks;
    }

    // products block: <product .../> self-closing
    const prodStart = src.indexOf('<products>');
    const prodEnd = src.indexOf('</products>');
    if (prodStart !== -1 && prodEnd !== -1) {
      const body = src.slice(prodStart + 10, prodEnd);
      const tagRe = /<product\s[^>]*\/>/g;
      let m;
      while ((m = tagRe.exec(body)) !== null) {
        const node = parseSelfClosing(m[0]);
        if (node) rec.products.push(node);
      }
    }
  }

  // --- Build global band list + id remap ---------------------------------
  // band key: article|name|height|thickness ; file-local id -> global id
  let sheet = null;
  const globalBands = [];
  for (let si = 0; si < parsed.length; si++) {
    const rec = parsed[si];
    for (const node of rec.materials) {
      if (node['-type'] === 'sheet') {
        if (!sheet && opts.materialName) {
          // prefer explicitly-provided sheet name if it matches
        }
        if (!sheet) sheet = { node, remap: { [node['-id']]: 1 } };
        continue;
      }
      // band
      const key = [node['-article'], node['-name'], node['-height'], node['-thickness']].join('|');
      if (!bandMap.has(key)) {
        bandMap.set(key, nextBandId++);
        globalBands.push(node);
      }
    }
  }

  // Build per-file remap: localId -> globalId
  const fileRemaps = [];
  for (let si = 0; si < parsed.length; si++) {
    const rec = parsed[si];
    const remap = {};
    for (const node of rec.materials) {
      if (node['-type'] === 'sheet') {
        remap[node['-id']] = 1;
      } else {
        const key = [node['-article'], node['-name'], node['-height'], node['-thickness']].join('|');
        remap[node['-id']] = bandMap.get(key);
      }
    }
    fileRemaps.push(remap);
  }

  // --- Collect details ----------------------------------------------------
  const mergedDetails = [];
  let detailAlphaId = 0;
  for (let si = 0; si < parsed.length; si++) {
    const remap = fileRemaps[si];
    for (const block of parsed[si].details) {
      detailAlphaId++;
      // parse detail opening tag to rewrite id= and material=
      const openMatch = block.match(/^(<detail\s[^>]*>)/s);
      if (!openMatch) { mergedDetails.push(block); continue; }
      let openTag = openMatch[1];
      const newOpen = openTag
        .replace(/\bid="\d+"/, 'id="' + detailAlphaId + '"')
        .replace(/\bmaterial="\d+"/, (mm) => {
          const old = (mm.match(/"(\d+)"/) || [])[1];
          const fixed = remap[old] || 1;
          return 'material="' + fixed + '"';
        });
      let body = block.slice(openMatch[0].length, block.length - '</detail>'.length);
      // remap edge param="N" and cornerOperation edgeMaterial="N"
      body = body.replace(/(\bparam)="(\d+)"/g, (mm, attr, val) => {
        const fixed = remap[val] || 1;
        return attr + '="' + fixed + '"';
      });
      body = body.replace(/(\bedgeMaterial)="(\d+)"/g, (mm, attr, val) => {
        const fixed = remap[val] || 1;
        return attr + '="' + fixed + '"';
      });
      mergedDetails.push(newOpen + body + '</detail>');
    }
  }

  // --- Collect products ---------------------------------------------------
  const mergedProducts = [];
  let prodId = 0;
  for (let si = 0; si < parsed.length; si++) {
    for (const node of parsed[si].products) {
      prodId++;
      const clone = Object.assign({}, node);
      clone['-id'] = prodId;
      mergedProducts.push(selfClosingTag('product', clone));
    }
  }

  // --- Folding data up -----------------------------------------------------
  const sheetName = (sheet && sheet.node['-name']) || (opts && opts.materialName) || '';
  const sheetCode = sheet ? sheet.node['-article'] : '';
  const sheetThickness = sheet ? sheet.node['-thickness'] : '';

  // --- Header block: copy verbatim from the first source file so the server
  // sees the same <creator> (id, version, bazisVersion) it already accepts.
  // Fall back to a hardcoded default only if the first source lacks it.
  const firstSrc = sources[0];
  let headerBlock = '<viyar version="27">\n<order delivery="" uuid="" />\n<creator id="Bazis2Viyar" version="5.10" bazisVersion="0" />\n<constructor id="dsp" site="" />';
  {
    const viyarOpen = firstSrc.indexOf('<viyar');
    const ctorEnd = firstSrc.indexOf('/>', firstSrc.indexOf('<constructor'));
    if (viyarOpen !== -1 && firstSrc.indexOf('<constructor') !== -1) {
      const afterCtor = firstSrc.indexOf('<constructor');
      const close = firstSrc.indexOf('/>', afterCtor);
      if (close !== -1) {
        // Take everything from "<viyar" up to and including the constructor's "/>".
        headerBlock = firstSrc.slice(viyarOpen, close + 2);
      }
    }
  }

  // --- Assemble XML --------------------------------------------------------
  const LF = '\n';
  let xml = '<?xml version="1.0" encoding="windows-1251" ?>' + '<project currency="" version="1" costOperation="0" costMaterial="0" cost="0" date="" orderDate="" productFilter="false">' + LF;
  xml += headerBlock + LF;

  xml += '<materials>' + LF;
  if (sheet) {
    const sNode = Object.assign({}, sheet.node);
    sNode['-id'] = 1;
    xml += selfClosingTag('material', sNode) + LF;
  } else {
    xml += '<material id="1" type="sheet" article="' + (sheetCode || '') + '" name="' + (sheetName || '') + '" width="3000" height="3000" thickness="' + (sheetThickness || '') + '" />' + LF;
  }
  globalBands.forEach(node => {
    const id = bandMap.get([node['-article'], node['-name'], node['-height'], node['-thickness']].join('|'));
    const bNode = Object.assign({}, node);
    bNode['-id'] = id;
    xml += selfClosingTag('material', bNode) + LF;
  });
  xml += '</materials>' + LF;

  xml += '<details>' + LF;
  mergedDetails.forEach(d => { xml += d + LF; });
  xml += '</details>' + LF;

  if (mergedProducts.length) {
    xml += '<products>' + LF;
    mergedProducts.forEach(p => { xml += p + LF; });
    xml += '</products>' + LF;
  }

  xml += '</viyar>' + LF;
  xml += '</project>';

  return {
    material: sheetName,
    code: sheetCode,
    thickness: sheetThickness,
    detailCount: mergedDetails.length,
    fileCount: sources.length,
    buffer: encodeWindows1251(xml)
  };
}

module.exports = { mergeProjectFiles };